apps/home/urls.py
from django.conf.urls import url
from apps.home import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contacts/', views.contacts, name='contacts'),
    url(r'^help/', views.yes_help, name='yes_help'),
    url(r'^about/', views.about, name='about'),
    url(r'^plans/', views.plans, name='plans'),
    url(r'^partner/', views.partner, name='partner'),
    url(r'^faq/', views.faq, name='faq'),
]

apps/user/urls.py
from django.conf.urls import url

from apps.user import views


urlpatterns = [

    url(r'^register/$', views.stsignup, name='stregister'),

    url(r'^register/(?P<user_pk>\d+)/$', views.signup , name='register'),

    url(r'^profile/$', views.profile, name='profile'),

    url(r'^redirect/',views.user_redirect, name='user_redirect'),

    url(r'^info/(?P<user_id>\d+)/$', views.info, name='info'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
]

investment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
# urlpatterns = (
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    url(r'^', include(('apps.home.urls', 'home'), namespace='home')),
    url(r'^user/', include(('apps.user.urls', 'user'), namespace='user')),
    url(r'^money/', include(('apps.money.urls', 'money'), namespace='money')),
    url(r'^referrals/', include(('apps.referrals.urls', 'referrals'), namespace='referrals')),
    url(r'^deposit/', include(('apps.deposit.urls', 'deposit'), namespace='deposit')),
    url(r'^panel/', include(('apps.panel.urls', 'panel'), namespace='panel')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
)

apps/user/models.py
# coding=utf-8
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.deposit.models import StatusBtc, StatusUsd


class Profile(models.Model):
    logo = models.ImageField('Logo', null=True, blank=True, upload_to='profile_images')

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    referal = models.ForeignKey(User, related_name='profile_referel', blank=True, null=True, on_delete=models.CASCADE)
    status_referal_usd = models.ForeignKey(StatusUsd, related_name='status_ref_usd', blank=True, null=True, on_delete=models.CASCADE)
    status_referal_btc = models.ForeignKey(StatusBtc, related_name='status_ref_btc', blank=True, null=True, on_delete=models.CASCADE)
    new_status_usd = models.ForeignKey(StatusUsd, related_name='status_usd', blank=True, null=True, on_delete=models.CASCADE)
    new_status_btc = models.ForeignKey(StatusBtc, related_name='status_btc', blank=True, null=True, on_delete=models.CASCADE)

    balance_usd = models.FloatField('Online Баласн USD', default=0)
    balance_btc = models.FloatField('Online Баласн BTC', default=0)

    zarab_usd = models.FloatField('Online Баланс вывода USD:', default=0)
    zarab_btc = models.FloatField('Online Баланс вывода BTC', default=0)

    zarab_usd_all = models.FloatField('Online Баланс вывода USD:', default=0)
    zarab_btc_all = models.FloatField('Online Баланс вывода BTC', default=0)

    bonus_usd = models.FloatField('Online Заработано Бонусов USD', default=0)
    bonus_btc = models.FloatField('Online Заработано Бонусов BTC', default=0)

    filled_usd = models.FloatField('Пополнил USD', default=0)
    filled_btc = models.FloatField('Пополнил BTC', default=0)

    out_usd = models.FloatField('Вывел USD', default=0)
    out_btc = models.FloatField('Вывел BTC', default=0)

    zarab_premia_usd = models.FloatField('Online Заработано Premia USD', default=0)
    zarab_premia_btc = models.FloatField('Online Заработано Premia BTC', default=0)

    out_bonus_usd = models.FloatField('Вывел Партнерские вознаграждения USD', default=0)
    out_bonus_btc = models.FloatField('Вывел Партнерские вознаграждения BTC', default=0)


    deposit_usd = models.FloatField('Cумма Депозит USD', default=0)
    deposit_btc = models.FloatField('Cумма Депозит BTC', default=0)


    sum_vivoda_usd = models.FloatField('Cумма вивода USD', default=0)
    sum_vivoda_btc = models.FloatField('Cумма вивода BTC', default=0)

    oborot_usd = models.FloatField('Оборот USD', default=0)
    oborot_btc = models.FloatField('Оборот BTC', default=0)

    expense = models.FloatField('Оборот BTC', default=0)

    phone = models.CharField('Телефон', blank=True, null=True, max_length=30)

    whatsapp = models.CharField(blank=True, null=True, max_length=30)

    viber = models.CharField(blank=True, null=True, max_length=30)

    skype = models.CharField(blank=True, null=True, max_length=30)

    url_facebook = models.CharField(blank=True, null=True, max_length=30)

    url_vk= models.CharField(blank=True, null=True, max_length=30)

    url_ok= models.CharField(blank=True, null=True, max_length=30)

    advcash= models.CharField(blank=True, null=True, max_length=30)

    bitcoin= models.CharField(blank=True, null=True, max_length=30)

    payeer= models.CharField(blank=True, null=True, max_length=30)

    perfectmoney= models.CharField(blank=True, null=True, max_length=30)

    visible = models.BooleanField(default=False)

    btn_active = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s' % self.user

    class Meta:
        verbose_name = '1. Пользователи'
        verbose_name_plural = '1. Пользователи'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if (instance.profile.referal == None):
        user = User.objects.filter(pk=1)[0]
        instance.profile.referal = user
    instance.profile.save()

apps/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from apps.user.models import Profile


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('skype', 'phone', 'url_facebook', 'url_vk', 'url_ok', 'payeer', 'perfectmoney',)

apps/user/views.py
import calendar
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login

from apps.deposit.models import StatusUsd, StatusBtc
from apps.user.models import Profile
from .forms import SignupForm, UserForm, ProfileForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils import six



@login_required
def profile(request):

    data = datetime.datetime.today().weekday()
    status = StatusUsd.objects.all()
    day_calendar = calendar.day_name[datetime.datetime.today().weekday()]

    if request.method == "POST":
        start = request.POST.get('start')

        if(start == 'yes'):
            Profile.objects.filter(user=request.user).update(btn_active=True)

    context = {

        'data': data,
        'day_calendar': day_calendar,
        'status': status,

    }

    return render(request, 'profile.html', context)



@login_required
@transaction.atomic
def user_redirect(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile, files=request.FILES or None, data=request.POST or None)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('user:profile')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    return render(request, 'redirect_user.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })



class TokenGenerator(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (
            six.text_type(user.pk) + six.text_type(timestamp) +
            six.text_type(user.is_active)
        )
account_activation_token = TokenGenerator()


def stsignup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'confirm_email.html')
    else:
        form = SignupForm()
    return render(request, 'register.html', {'form': form})



def info(request, user_id):

    profile_user = get_object_or_404(User, pk=user_id)
    referrals = Profile.objects.filter(referal=profile_user).order_by('-id')

    context = {

        'referrals': referrals,
        'profile_user': profile_user,


    }

    return render(request, 'user_info.html', context)


def signup(request, user_pk):

    try:
        request.session['my_referal'] = user_pk
        my_referal = request.session['my_referal']
    except:
        request.session['my_referal'] = 1
        my_referal = 1

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'confirm_email.html')
    else:
        form = SignupForm()
    return render(request, 'register.html', {'form': form, 'my_referal': my_referal})


def activate(request, uidb64, token):

    try:
        my_referal = request.session['my_referal']
    except:
        request.session['my_referal'] = 1
        my_referal = 1

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True

        Profile.objects.filter(pk=user.pk).update(status_referal_usd=get_object_or_404(StatusUsd, pk=2),
                                                  status_referal_btc=get_object_or_404(StatusBtc, pk=2),
                                                  referal=get_object_or_404(Profile, pk=my_referal))

        user.save()
        login(request, user)
        return render(request, 'email_confirmation.html')
    else:
        return render(request, 'link_invalid.html')

apps/user/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

apps/user/templates/confirm_email.html
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Template" />
    <meta name="author" content="SmartUniversity" />
    <title>Подтверждение Email</title>
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />
	<!-- icons -->
    <link href="/static/panel/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="/static/panel/assets/plugins/iconic/css/material-design-iconic-font.min.css">
    <!-- bootstrap -->
	<link href="/static/panel/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- style -->
    <link rel="stylesheet" href="/static/panel/assets/css/pages/extra_pages.css">
	<!-- favicon -->
    <link rel="shortcut icon" href="/static/panel/assets/img/favicon.ico" />
</head>
<body>
    <div class="limiter">
		<div class="container-login100 page-background">
			<div class="wrap-login100">
                 <div class="text-center">
                <p style="color: white">Вам на почту отправлено письмо.</p>
                <p style="color: white">Подтвердите вашу учётную запись</p>
                 </div>
                <div class="text-center" style="margin-top: 10px;">
                    <a href="{% url 'home:home' %}" style="color: white">Главная</a>
                </div>
			</div>
		</div>
	</div>
    <!-- start js include path -->
    <script src="/static/panel/assets/plugins/jquery/jquery.min.js" ></script>
    <!-- bootstrap -->
    <script src="/static/panel/assets/plugins/bootstrap/js/bootstrap.min.js" ></script>
    <script src="/static/panel/assets/js/pages/extra_pages/login.js" ></script>
    <!-- end js include path -->
</body>
</html>

apps/user/templates/email_confirmation.html
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Template" />
    <meta name="author" content="SmartUniversity" />
    <title>Подтверждение Email</title>
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />
	<!-- icons -->
    <link href="/static/panel/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="/static/panel/assets/plugins/iconic/css/material-design-iconic-font.min.css">
    <!-- bootstrap -->
	<link href="/static/panel/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- style -->
    <link rel="stylesheet" href="/static/panel/assets/css/pages/extra_pages.css">
	<!-- favicon -->
    <link rel="shortcut icon" href="/static/panel/assets/img/favicon.ico" />
</head>
<body>
    <div class="limiter">
		<div class="container-login100 page-background">
			<div class="wrap-login100">
                 <div class="text-center">
                <p style="color: white">Ваша учётная запись успешно подтверждена</p>
                
                 </div>
                <div class="text-center">
                    <a href="{% url 'home:home' %}" style="color: white">Главная</a>
                </div>
			</div>
		</div>
	</div>
    <!-- start js include path -->
    <script src="/static/panel/assets/plugins/jquery/jquery.min.js" ></script>
    <!-- bootstrap -->
    <script src="/static/panel/assets/plugins/bootstrap/js/bootstrap.min.js" ></script>
    <script src="/static/panel/assets/js/pages/extra_pages/login.js" ></script>
    <!-- end js include path -->
</body>
</html>

apps/user/templates/link_invalid.html
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Template" />
    <meta name="author" content="SmartUniversity" />
    <title>Подтверждение Email</title>
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />
	<!-- icons -->
    <link href="/static/panel/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="/static/panel/assets/plugins/iconic/css/material-design-iconic-font.min.css">
    <!-- bootstrap -->
	<link href="/static/panel/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- style -->
    <link rel="stylesheet" href="/static/panel/assets/css/pages/extra_pages.css">
	<!-- favicon -->
    <link rel="shortcut icon" href="/static/panel/assets/img/favicon.ico" />
</head>
<body>
    <div class="limiter">
		<div class="container-login100 page-background">
			<div class="wrap-login100">
                 <div class="text-center">
                <p style="color: white">Ссылка не действительна</p>

                 </div>
                <div class="text-center">
                    <a href="{% url 'home:home' %}" style="color: white">Главная</a>
                </div>
			</div>
		</div>
	</div>
    <!-- start js include path -->
    <script src="/static/panel/assets/plugins/jquery/jquery.min.js" ></script>
    <!-- bootstrap -->
    <script src="/static/panel/assets/plugins/bootstrap/js/bootstrap.min.js" ></script>
    <script src="/static/panel/assets/js/pages/extra_pages/login.js" ></script>
    <!-- end js include path -->
</body>
</html>

apps/user/templates/redirect_user.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Обновления профиля</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{% url 'home:home' %}">Главная</a>&nbsp;<i class="fa fa-angle-right"></i></li>
                        <li class="active">Обновления профиля</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="card  card-box">
                        <div class="card-header">
                            <form method="post">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h4><i class="fa fa-user" aria-hidden="true"></i> Пользователь: <i>{{ request.user }}</i></h4>
                                        <hr>
                                    </div>
                                    {% csrf_token %}
                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-user" aria-hidden="true"></i> Им'я</h5>
                                        <div>{{ user_form.first_name|add_class:'form-control input-lg'}}</div>
                                    </div>

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-user-o" aria-hidden="true"></i> Фамилия</h5>
                                        <div>{{ user_form.last_name|add_class:'form-control input-lg'}}</div>
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                        <br>
                                        <button name="Submit1" class="btn  btn-primary">Сохранить</button>
                                    </div>
                                </div>
{#                            </form>#}
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-box">
                        <div class="card-header">
{#                            <form method="post">#}
                                <div class="row">
                                    <div class="col-md-12">
                                        <h4><i class="fa fa-phone" aria-hidden="true"></i> Связь</h4>
                                        <hr>
                                    </div>
{#                                    {% csrf_token %}#}
                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-skype" aria-hidden="true"></i> Skype:</h5>
                                        <div>{{ profile_form.skype|add_class:'form-control input-lg'}}</div>
                                    </div>

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-phone" aria-hidden="true"></i> Номер телефона:</h5>
                                        <div>{{ profile_form.phone|add_class:'form-control input-lg'}}</div>
                                    </div>

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-vk" aria-hidden="true"></i> Вконтакте:</h5>
                                        <div>{{ profile_form.url_vk|add_class:'form-control input-lg'}}</div>
                                    </div>

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-odnoklassniki" aria-hidden="true"></i> Одноклассники:</h5>
                                        <div>{{ profile_form.url_ok|add_class:'form-control input-lg'}}</div>
                                    </div>

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-facebook" aria-hidden="true"></i> Facebook:</h5>
                                        <div>{{ profile_form.url_facebook|add_class:'form-control input-lg'}}</div>
                                    </div>
                                     <div class="col-md-12 col-sm-12 col-xs-12">
                                            <br>
                                        <button name="Submit1" class="btn  btn-primary">Сохранить</button>
                                     </div>
                                </div>
{#                            </form>#}
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card card-box">
                        <div class="card-header">
{#                            <form method="post">#}
                                <div class="row">
                                    <div class="col-md-12">
                                        <h4><i class="fa fa-money" aria-hidden="true"></i> Платежные реквизиты</h4>
                                        <hr>
                                    </div>
{#                                    {% csrf_token %}#}

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-credit-card" aria-hidden="true"></i> Payeer:</h5>
                                        <div>{{ profile_form.payeer|add_class:'form-control input-lg'}}</div>
                                    </div>

                                    <div class="col-md-12">
                                        <h5 style="padding-left: 10px"><i class="fa fa-credit-card" aria-hidden="true"></i> Perfectmoney:</h5>
                                        <div>{{ profile_form.perfectmoney|add_class:'form-control input-lg'}}</div>
                                    </div>

                                     <div class="col-md-12 col-sm-12 col-xs-12">
                                            <br>
                                        <button name="Submit1" class="btn  btn-primary">Сохранить</button>
                                     </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

apps/user/templates/register.html
{#<html>#}
{#  <head>#}
{#    <title>Регистрация</title>#}
{#  </head>#}
{#  <body>#}
{#    <form action="" method="post">#}
{#      {% csrf_token %}#}
{#      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->#}
{#      {{ form.as_p }}#}
{#      <button type="submit">Зарегистрироваться</button>#}
{#    </form>#}
{#  {{ my_referal }}#}
{##}
{#  </body>#}
{#</html>#}
{% load i18n %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Template" />
    <meta name="author" content="SmartUniversity" />
    <title>Регистрация</title>
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />
	<!-- icons -->
    <link href="/static/panel/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="/static/panel/assets/plugins/iconic/css/material-design-iconic-font.min.css">
    <!-- bootstrap -->
	<link href="/static/panel/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- style -->
    <link rel="stylesheet" href="/static/panel/assets/css/pages/extra_pages.css">
	<!-- favicon -->
    <link rel="shortcut icon" href="/static/panel/assets/img/favicon.ico" />
</head>
<body>
{#    <div class="limiter">#}
		<div class="container-login100 page-background">
			<div style="background: #1d282d" class="wrap-login100">


                <form action="" method="post">
                    {% csrf_token %}
                    <span class="login100-form-logo">
                    <a href="{% url 'home:home' %}">
                        <img src="/static/site/images/header/logo_d2.png" alt="">
                    </a>
                    </span>
                    <span class="login100-form-title p-b-34 p-t-27">
                        Регистрация
                    </span>


                    {% if form.errors %}
                        <div style="padding: 10px; border: 2px solid #cc5e00; border-radius: 25px; background: #d3d7d1; ">
                            <p>{{ form.errors }}</p>
                        </div>
                    {% endif %}
                    <br>

                    <div class="wrap-input100 validate-input" data-validate = "Enter username">
                        {% render_field form.username class="input100"  placeholder="Username" %}
                    </div><!-- /.col-sm-6 -->
                    <div class="wrap-input100 validate-input" data-validate="Enter password">
                        {% render_field form.email class="input100"  placeholder="Email" %}
                    </div>
                    <div class="wrap-input100 validate-input" data-validate="Enter password">
                        {% render_field form.password1 class="input100"  placeholder="Password" %}
                    </div>
                    <div class="wrap-input100 validate-input" data-validate="Enter password">
                        {% render_field form.password2 class="input100"  placeholder="Confirm Password" %}
                    </div>
                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Зарегистрироваться
                        </button>
                    </div>
                    <br>
                </form>
                {{ my_referal }}


			</div>
		</div>
{#	</div>#}
    <!-- start js include path -->
    <script src="/static/panel/assets/plugins/jquery/jquery.min.js" ></script>
    <!-- bootstrap -->
    <script src="/static/panel/assets/plugins/bootstrap/js/bootstrap.min.js" ></script>
    <script src="/static/panel/assets/js/pages/extra_pages/login.js" ></script>
    <!-- end js include path -->
</body>
</html>