apps/home/urls.py
from django.conf.urls import url
from apps.home import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contacts/', views.contacts, name='contacts'),
    url(r'^help/', views.yes_help, name='yes_help'),
    url(r'^about/', views.about, name='about'),
    url(r'^plans/', views.plans, name='plans'),
    url(r'^partner/', views.partner, name='partner'),
    url(r'^faq/', views.faq, name='faq'),
]

apps/user/urls.py
from django.conf.urls import url

from apps.user import views


urlpatterns = [

    url(r'^register/$', views.stsignup, name='stregister'),

    url(r'^register/(?P<user_pk>\d+)/$', views.signup , name='register'),

    url(r'^profile/$', views.profile, name='profile'),

    url(r'^redirect/',views.user_redirect, name='user_redirect'),

    url(r'^info/(?P<user_id>\d+)/$', views.info, name='info'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
]

investment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
# urlpatterns = (
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    url(r'^', include(('apps.home.urls', 'home'), namespace='home')),
    url(r'^user/', include(('apps.user.urls', 'user'), namespace='user')),
    url(r'^money/', include(('apps.money.urls', 'money'), namespace='money')),
    url(r'^referrals/', include(('apps.referrals.urls', 'referrals'), namespace='referrals')),
    url(r'^deposit/', include(('apps.deposit.urls', 'deposit'), namespace='deposit')),
    url(r'^panel/', include(('apps.panel.urls', 'panel'), namespace='panel')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
)

templates/base_admin.html
{% extends 'base_full_admin.html' %}
{% load i18n %}


{% block header %}
<!-- preloader Start -->
    <div id="preloader">
        <div id="status"><img src="/static/site/images/header/bitcoin-globe.gif" id="preloader_image" alt="loader">
        </div>
    </div>
    <!-- btc top header wrapper Start -->
    <div section-scroll='0' class="wd_scroll_wrap">
        <div class="btc_top_header_main_wrapper">
            <div class="container-fluid">
                <div class="btc_left_top_header_wrapper">
                    <p class="btc_topheader_welcome_pera"><b>{% trans 'Добро пожаловать в Deltus.biz' %}</b></p>
                    <div style="visibility: hidden;" id="ticker_window">
                        <div id="day_and_time">
                            <p style="visibility: hidden;" id="date" class="hidden-xs"></p>
                            <p></p>

                        </div>

                    </div>

                </div>
                <div class="btc_right_top_header_wrapper">
                    <ul>
                        <li class=""><a style="padding: 0px" href="{% url 'user:stregister' %}"> <i class="fa fa-user" aria-hidden="true"></i> Регистрация </a></li>

{#                        <li class="btc_topheader_welcome_pera"><i class="flaticon-phone-call"></i> o.site@gmail.com</li>#}
                        {% if request.user.is_active %}
                             <li><a href="{% url 'logout' %}"> <i class="fa fa-user" aria-hidden="true"></i> Выход </a></li>
                        {% else %}
                            <li><a href="{% url 'user:profile' %}"> <i class="fa fa-user" aria-hidden="true"></i> Вход </a></li>
                        {% endif %}


                        <li>
                            <span> <a style="padding: 0px; padding-left: 10px" href="/en/{{ CURRENT_URL }}">EN</a></span>
                        </li>
                        <li>
                            <span> <a style="padding: 0px; padding-left: 10px" href="/ru/{{ CURRENT_URL }}">RU</a></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- btc top header wrapper End -->
        <!-- Header Wrapper Start -->
        <div style="background: #1d282d" class="gc_main_menu_wrapper">
            <div class="container-fluid">
                <div id="search_open" class="gc_search_box">
                    <input type="text" placeholder="Search here">
                    <button><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 hidden-xs">
                        <div class="gc_header_wrapper">
                            <div class="gc_logo">
                                <a href="{% url 'home:home' %}"><img src="/static/site/images/header/logo_d2.png" width="90" alt="Logo"></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="header-area hidden-menu-bar stick" id="sticker">
                        <!-- mainmenu start -->
                        <div class="gc_right_menu hidden-xs">
                            <ul>
                                {% if request.user.is_active %}
                                <li class="btc_join_navi_btn"><a href="{% url 'user:profile' %}"><b>{{ request.user }}</b></a></li>
                                    {% else %}
                                    <li class="btc_join_navi_btn"><a href="{% url 'user:profile' %}"><b>Вход</b></a></li>
                                {% endif %}
                            </ul>
                        </div>
                        <div class="mainmenu hidden-xs">
                            <ul>
                                <li class="gc_main_navigation parent"><a style="color: white" href="{% url 'home:home' %}" class="gc_main_navigation">Главная</a></li>

                                <li class="gc_main_navigation parent"><a style="color: white" href="{% url 'home:about' %}" class="gc_main_navigation">О нас</a></li>

                                <li class="gc_main_navigation parent"><a style="color: white" href="{% url 'home:plans' %}" class="gc_main_navigation">Планы развития</a></li>

                                <li class="gc_main_navigation parent"><a style="color: white" href="{% url 'home:partner' %}" class="gc_main_navigation">Инвестиции</a></li>

                                <li class="gc_main_navigation parent"><a style="color: white" href="{% url 'home:faq' %}" class="gc_main_navigation">FAQ</a></li>

{#                                <li class="gc_main_navigation parent"><a href="contact.html" class="gc_main_navigation">Новости</a></li>#}

                                <li class="gc_main_navigation parent"><a style="color: white" href="{% url 'home:contacts' %}" class="gc_main_navigation">Контакты</a></li>
                            </ul>
                        </div>
                        <!-- mainmenu end -->
                        <!-- mobile menu area start -->
                        <div class="rp_mobail_menu_main_wrapper visible-xs">
                            <div class="row">
                                <div class="col-xs-6">
                                    <div class="gc_logo">
                                        <a href="{% url 'home:home' %}"><img src="/static/site/images/header/logo_d2.png" alt="Logo" title="Bit Money"></a>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div id="toggle">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 31.177 31.177" style="enable-background:new 0 0 31.177 31.177;" xml:space="preserve" width="25px" height="25px"><g><g><path class="menubar" d="M30.23,1.775H0.946c-0.489,0-0.887-0.398-0.887-0.888S0.457,0,0.946,0H30.23    c0.49,0,0.888,0.398,0.888,0.888S30.72,1.775,30.23,1.775z" fill="#000000"/></g><g><path class="menubar" d="M30.23,9.126H12.069c-0.49,0-0.888-0.398-0.888-0.888c0-0.49,0.398-0.888,0.888-0.888H30.23    c0.49,0,0.888,0.397,0.888,0.888C31.118,8.729,30.72,9.126,30.23,9.126z" fill="#000000"/></g><g><path class="menubar" d="M30.23,16.477H0.946c-0.489,0-0.887-0.398-0.887-0.888c0-0.49,0.398-0.888,0.887-0.888H30.23    c0.49,0,0.888,0.397,0.888,0.888C31.118,16.079,30.72,16.477,30.23,16.477z" fill="#000000"/></g><g><path class="menubar" d="M30.23,23.826H12.069c-0.49,0-0.888-0.396-0.888-0.887c0-0.49,0.398-0.888,0.888-0.888H30.23    c0.49,0,0.888,0.397,0.888,0.888C31.118,23.43,30.72,23.826,30.23,23.826z" fill="#000000"/></g><g><path class="menubar" d="M30.23,31.177H0.946c-0.489,0-0.887-0.396-0.887-0.887c0-0.49,0.398-0.888,0.887-0.888H30.23    c0.49,0,0.888,0.398,0.888,0.888C31.118,30.78,30.72,31.177,30.23,31.177z" fill="#000000"/></g></g></svg>
                                    </div>
                                </div>
                            </div>

                            <div id="sidebar">
                                <h1><a href="#">Bit Money</a></h1>
                                <div id="toggle_close">&times;</div>
                                <div id='cssmenu'>
                                    <ul>
                                        <li class="gc_main_navigation parent"><a href="{% url 'home:home' %}" class="gc_main_navigation">Главная</a></li>

                                        <li class="gc_main_navigation parent"><a href="{% url 'home:about' %}" class="gc_main_navigation">О нас</a></li>

                                        <li class="gc_main_navigation parent"><a href="{% url 'home:plans' %}" class="gc_main_navigation">Планы развития</a></li>

                                        <li class="gc_main_navigation parent"><a href="{% url 'home:partner' %}" class="gc_main_navigation">Инвестиции</a></li>

                                        <li class="gc_main_navigation parent"><a href="{% url 'home:faq' %}" class="gc_main_navigation">FAQ</a></li>

        {#                                <li class="gc_main_navigation parent"><a href="contact.html" class="gc_main_navigation">Новости</a></li>#}

                                        <li class="gc_main_navigation parent"><a href="{% url 'home:contacts' %}" class="gc_main_navigation">Контакты</a></li>

                                        <br>
                                        {% if request.user.is_active %}
                                            <li class="btc_join_navi_btn"><a href="{% url 'user:profile' %}"><b>{{ request.user }}</b></a></li>
                                            {% else %}
                                            <li class="btc_join_navi_btn"><a href="{% url 'user:profile' %}"><b>Вход</b></a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <!-- mobile menu area end -->
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block wrapper %}
    {% block content_wrapper %}
        {% block content %}

        {% endblock %}
    {% endblock %}
{% endblock %}


{% block footer %}
    <div class="btc_footer_main_wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">
                        <div class="btc_footer_logo_left">
                            <a href="#"><img src="/static/site/images/header/logo_d2.png" style="height: 80px;" alt="logo"/></a>
                        </div>
{#                        <div class="btc_footer_logo_right">#}
{#                            <p>The Central Common Government Offices#}
{#                                No. 7, 3-2-1 Kasumigaseki, Chiyoda-ku,#}
{#                                Токио, Япония#}
{#                            </p>#}
{#                        </div>#}
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 col-lg-offset-1g col-md-offset-1">
                        <div class="btc_footer_social_wrapper">
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-telegram"></i></a></li>
                                <li><a href="#"><i class="fa fa-btc"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- btc footer Wrapper End -->
        <!-- btc bottom footer Wrapper Start -->
        <div class="btc_bottom_footer_main_wrapper">
            <a href="javascript:void(0);" id="scroll" title="Scroll to Top" style="display: none;"><span class="fa fa-angle-double-up"></span></a>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                        <div class="btc_bottom_footer_left">
                            <p>© Deltus.biz | Все права защищены</p>
                        </div>
                    </div>
{#                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 hidden-sm hidden-xs">#}
{#                        <div class="btc_bottom_footer_right">#}
{#                            <ul>#}
{#                                <p>Terms and Condition</p>#}
{#                            </ul>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base_full_admin.html
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>{% block page_title %}{% endblock %}</title>

        <meta charset="utf-8">
        <meta name="keywords" content="{% block meta_k %}{% endblock %}">
        <meta name="description" content="{% block meta_d %}{% endblock %}">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="robots" content="index,follow" />
        <meta http-equiv="Content-Language" content="{{ LANGUAGE_CODE }}" />
        <meta name="author" content="Andrei Onishchuk" />

        {% for lang in LANGUAGES %}
            <link rel="alternate" hreflang="{{ lang.0 }}" href="http://{{ request.META.HTTP_HOST }}/{{ lang.0 }}/{{ CURRENT_URL }}" />
        {% endfor %}

        <link rel="shortcut icon" type="image/ico" href="{{ IMG_URL }}favicon.ico" />


        {% block css %}

            <link rel="stylesheet" type="text/css" href="/static/site/css/animate.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/bootstrap.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/font-awesome.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/fonts.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/flaticon.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/owl.carousel.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/owl.theme.default.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/js/plugin/rs_slider/layers.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/js/plugin/rs_slider/navigation.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/js/plugin/rs_slider/settings.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/style.css" />
            <link rel="stylesheet" type="text/css" href="/static/site/css/responsive.css" />
            <!-- favicon links -->
            <link rel="shortcut icon" type="image/png" href="/static/site/images/header/favicon.ico" />

        {% endblock %}

    </head>

    <body class="app sidebar-fixed aside-menu-off-canvas aside-menu-hidden header-fixed ">

        {% block body %}

            {% block header %}{% endblock %}

            {% block wrapper %}{% endblock %}

            {% block footer %}{% endblock %}

        {% endblock %}

    </body>

    {% block js %}
        <script src="/static/site/js/jquery_min.js"></script>
        <script src="/static/site/js/bootstrap.js"></script>
        <script src="/static/site/js/modernizr.js"></script>
        <script src="/static/site/js/parallax.min.js"></script>
        <script src="/static/site/js/owl.carousel.js"></script>
        <script src="/static/site/js/bit_timer.js"></script>
        <script src="/static/site/js/Chart.bundle.js"></script>
        <script src="/static/site/js/chart.js"></script>
        <script src="/static/site/js/plugin/rs_slider/jquery.themepunch.tools.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/jquery.themepunch.revolution.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.addon.snow.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.actions.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.carousel.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.kenburn.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.layeranimation.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.migration.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.navigation.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.parallax.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.slideanims.min.js"></script>
        <script src="/static/site/js/plugin/rs_slider/revolution.extension.video.min.js"></script>
        <script src="/static/site/js/custom.js"></script>
    {% endblock %}

</html>

templates/base_full_panel.html
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>{% block page_title %}{% endblock %}</title>

        <meta charset="utf-8">
        <meta name="keywords" content="{% block meta_k %}{% endblock %}">
        <meta name="description" content="{% block meta_d %}{% endblock %}">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="robots" content="index,follow" />
        <meta http-equiv="Content-Language" content="{{ LANGUAGE_CODE }}" />
        <meta name="author" content="Andrei Onishchuk" />

        {% for lang in LANGUAGES %}
            <link rel="alternate" hreflang="{{ lang.0 }}" href="http://{{ request.META.HTTP_HOST }}/{{ lang.0 }}/{{ CURRENT_URL }}" />
        {% endfor %}

        <link rel="shortcut icon" type="image/ico" href="{{ IMG_URL }}favicon.ico" />


        {% block css %}

            <!-- google font -->
            <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />
            <!-- icons -->
            <link href="/static/panel/assets/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
            <link href="/static/panel/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
            <!--bootstrap -->
            <link href="/static/panel/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            <!-- Material Design Lite CSS -->
            <link rel="stylesheet" href="/static/panel/assets/plugins/material/material.min.css">
            <link rel="stylesheet" href="/static/panel/assets/css/material_style.css">
            <!-- animation -->
            <link href="/static/panel/assets/css/pages/animate_page.css" rel="stylesheet">
            <!-- Template Styles -->
            <link href="/static/panel/assets/css/style.css" rel="stylesheet" type="text/css" />
            <link href="/static/panel/assets/css/plugins.min.css" rel="stylesheet" type="text/css" />
            <link href="/static/panel/assets/css/responsive.css" rel="stylesheet" type="text/css" />
            <link href="/static/panel/assets/css/theme-color.css" rel="stylesheet" type="text/css" />
            <!-- favicon -->
            <link rel="shortcut icon" href="/static/panel/assets/img/favicon.ico" />

        {% endblock %}

    </head>

    <body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-dark">

        {% block body %}

            {% block header %}{% endblock %}

            {% block wrapper %}{% endblock %}

            {% block footer %}{% endblock %}

        {% endblock %}

    </body>

    {% block js %}



       <script src="/static/panel/assets/plugins/jquery/jquery.min.js" ></script>
        <script src="/static/panel/assets/plugins/popper/popper.min.js" ></script>
        <script src="/static/panel/assets/plugins/jquery-blockui/jquery.blockui.min.js" ></script>
        <script src="/static/panel/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
        <!-- bootstrap -->
        <script src="/static/panel/assets/plugins/bootstrap/js/bootstrap.min.js" ></script>
        <!-- Common js-->
        <script src="/static/panel/assets/js/app.js" ></script>
        <script src="/static/panel/assets/js/layout.js" ></script>
        <script src="/static/panel/assets/js/theme-color.js" ></script>
        <!-- Material -->
        <script src="/static/panel/assets/plugins/material/material.min.js"></script>
        <!-- animation -->
        <script src="/static/panel/assets/js/pages/ui/animations.js" ></script>

    {% endblock %}

</html>