apps/money/urls.py
from django.conf.urls import url

from apps.money import views


urlpatterns = [

    url(r'^refill/$', views.refill, name='refill'),

    url(r'^issuance/$', views.issuance, name='issuance'),

    url(r'^refill-perfect/$', views.refill_perfect, name='refill_perfect'),

    url(r'^refill-payeer/$', views.refill_payeer, name='refill_payeer'),

    url(r'^refill-perfect/ok/$', views.refill_perfect_add, name='refill_perfect_ok'),

    url(r'^refill-perfect/(?P<perfect_pk>\w+)/$', views.refill_perfect_add, name='refill_perfect_add'),

    url(r'^refill-payeer/yes/$', views.refill_payeer_add, name='refill_payeer_add'),

    url(r'^issuance-perfect/$', views.issuance_perfect, name='issuance_perfect'),

    url(r'^issuance-payeer/$', views.issuance_payeer, name='issuance_payeer'),


    url(r'^perfect/admin/$', views.perfect_admin, name='perfect_admin'),



    url(r'^transfer/$', views.transfer_money, name='transfer_money'),

    url(r'^transferkopilka/$', views.transferkopilka, name='transferkopilka'),

    url(r'^transfervivod/$', views.transfervivod, name='transfervivod'),

    url(r'^transferuser/$', views.transferuser, name='transferuser'),

    url(r'^transfer/ok/$', views.transfer_money_ok, name='transfer_money_ok'),

    url(r'^transfer/ok/vivod/$', views.transfer_money_ok_vivod, name='transfer_money_ok_vivod'),

    url(r'^transfer/no/$', views.transfer_money_no, name='transfer_money_no'),


    url(r'^transfer/expense/bali/$', views.transfer_money_expense_in_bali, name='transfer_money_expense_in_bali'),

    url(r'^transfer/expense/bali/basket/$', views.transfer_money_expense_in_bali_basket, name='transfer_money_expense_in_bali_basket'),







    url(r'^transfer/obtaining/in/expense/$', views.transfer_money_vivod_in_activation, name='transfer_money_vivod_in_activation'),

    url(r'^transfer/obtaining/in/expense/basket/$', views.transfer_money_vivod_in_activation_basket, name='transfer_money_vivod_in_activation_basket'),


    url(r'^transfer/bali/in/expense/$', views.transfer_bali_in_activation, name='transfer_bali_in_activation'),

    url(r'^transfer/bali/in/expense/basket/$', views.transfer_bali_in_activation_basket, name='transfer_bali_in_activation_basket'),


    url(r'^transfer/obtaining/in/expense/user$', views.transfer_vivod_in_activation_user, name='transfer_vivod_in_activation_user'),

    url(r'^transfer/obtaining/in/expense/user/basket/$', views.transfer_vivod_in_activation_user_basket, name='transfer_bali_in_activation_basket'),

]

apps/panel/urls.py
from django.conf.urls import url

from apps.panel import views


urlpatterns = [

    url(r'^$', views.panel, name='panel'),

    url(r'deposit/$', views.panel_deposit, name='panel_deposit'),

    url(r'^panel_payeer_output/', views.panel_payeer_output, name='panel_payeer_output'),

    url(r'^history/usd/', views.panel_history_usd, name='panel_history_usd'),

]

investment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
# urlpatterns = (
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    url(r'^', include(('apps.home.urls', 'home'), namespace='home')),
    url(r'^user/', include(('apps.user.urls', 'user'), namespace='user')),
    url(r'^money/', include(('apps.money.urls', 'money'), namespace='money')),
    url(r'^referrals/', include(('apps.referrals.urls', 'referrals'), namespace='referrals')),
    url(r'^deposit/', include(('apps.deposit.urls', 'deposit'), namespace='deposit')),
    url(r'^panel/', include(('apps.panel.urls', 'panel'), namespace='panel')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
)

apps/panel/views.py
# coding=utf-8
import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.db.models import F
from django.shortcuts import render, redirect, get_object_or_404

from apps.deposit.models import DepositUsd, DepositBTC, CategoryUSD, HistoryUsd
from apps.money.PerfectMoney import PerfectMoney
from apps.money.models import PayeerSubtract
from apps.payeer.api import PayeerApi
from apps.user.models import Profile
from datetime import date


def panel(request):

    # # Баланс payeer
    account = 'P1012357967'
    api_id = '792548463'
    api_pass = 'j9d6BAvRGowgJyNN'
    balanse_payeer = PayeerApi(account, api_id, api_pass).get_balance()
    balanse_payeer = balanse_payeer.get('USD').get('DOSTUPNO')

    account = '3310706'
    password = 'zN3Ht7vV'

    pm = PerfectMoney(account, password)
    res = pm.balance()
    pr_balans_perfect = str(res.get('U19769559'))
    print(pr_balans_perfect)

    context = {

        'balanse_payeer': balanse_payeer,
        'pr_balans_perfect': pr_balans_perfect,

    }
    return render(request, 'panel.html', context)


def marketing_usd(request, deposit):

    if (deposit.user.profile.btn_active == True and deposit.activate == True):
        cat_depos = CategoryUSD.objects.all().order_by('-id')[0]
        deposit = DepositUsd.objects.filter(pk=deposit.pk)[0]

        datatime = datetime.datetime.now()
        if (datatime.day != deposit.datetime.day or datatime.month != deposit.datetime.month or datatime.year != deposit.datetime.year):
            DepositUsd.objects.filter(pk=deposit.pk).update(count_day=F('count_day')+1,
                                                            zarabotano=F('zarabotano')+(cat_depos.suma * deposit.sum)/100)

            Profile.objects.filter(user=deposit.user).update(zarab_usd=F('zarab_usd')+(cat_depos.suma * deposit.sum)/100,
                                                             zarab_usd_all=F('zarab_usd_all')+(cat_depos.suma * deposit.sum)/100)

            print("New history")
            new_history = HistoryUsd(users=deposit.user, deposit=deposit, category=cat_depos,
                                     sponsor=deposit.user, maseger='Deposit', number=(cat_depos.suma * deposit.sum)/100,
                                     datetime=date.today())
            new_history.save()

    else:
        cat_depos = CategoryUSD.objects.all().order_by('-id')[0]
        new_history = HistoryUsd(users=deposit.user, deposit=deposit, category=cat_depos,
                                 sponsor=deposit.user, maseger='No active button', number=0,
                                 datetime=date.today())
        new_history.save()

    if (deposit.count_day >= 365):
        DepositUsd.objects.filter(pk=deposit.pk).update(activate=False)


def panel_deposit(request):

    cat_usd = CategoryUSD.objects.all().order_by('-id')[0]

    count_all_deposit = DepositUsd.objects.filter(activate=True, end=False).count()
    count_active_deposit_usd = 0
    count_active_deposit_no_active_user_usd = 0
    count_history_usd = HistoryUsd.objects.filter(datetime=date.today(), bonus=False, oborot=False).count()
    active_deposit_usd = DepositUsd.objects.filter(activate=True, end=False)
    for depos in active_deposit_usd:
        if (depos.user.profile.btn_active == True):
            count_active_deposit_usd += 1
        else:
            count_active_deposit_no_active_user_usd += 1


    count_all_user = Profile.objects.all().count()
    count_active_user = Profile.objects.filter(btn_active=True).count()
    count_usd_depos = DepositUsd.objects.filter(user=request.user, end=False, activate=True).count()
    count_btc_depos = DepositBTC.objects.filter(user=request.user, end=False, activate=True).count()

    if request.method == "POST":
        name_category = request.POST.get('name_category')

        if(name_category == 'usd'):
            liva_usd = request.POST.get('liva')
            prava_usd = request.POST.get('prava')
            print(liva_usd)
            print(prava_usd)

            all_dep_usd = DepositUsd.objects.filter(end=False, activate=True)[int(liva_usd):int(prava_usd)]
            for dep in all_dep_usd:
                marketing_usd(request, dep)

            return redirect(request.path)

        if (name_category == 'bts'):
            all_dep_usd = DepositBTC.objects.filter(end=False, activate=True)
            for dep in all_dep_usd:
                print(dep)
                print(dep.user)


            return redirect(request.path)

        if (name_category == 'active_user'):
            all_profile = Profile.objects.filter(btn_active=True)
            for profile in all_profile:
                print(profile)
                Profile.objects.filter(pk=profile.pk).update(btn_active=False)

            return redirect(request.path)

    context = {

        'count_all_user': count_all_user,
        'count_active_user': count_active_user,
        'count_usd_depos': count_usd_depos,
        'count_btc_depos': count_btc_depos,

        'count_active_deposit_usd': count_active_deposit_usd,
        'count_active_deposit_no_active_user_usd': count_active_deposit_no_active_user_usd,
        'count_all_deposit': count_all_deposit,
        'count_history_usd': count_history_usd,
        'cat_usd': cat_usd,

    }
    return render(request, 'panel_deposit.html', context)



def panel_payeer_output(request):

    account = 'P1012357967'
    api_id = '792548463'
    api_pass = 'j9d6BAvRGowgJyNN'
    balanse_payeer = PayeerApi(account, api_id, api_pass).get_balance()
    balanse_payeer = balanse_payeer.get('USD').get('DOSTUPNO')

    payeer_outputs = PayeerSubtract.objects.filter(visible=True)

    if request.method == "POST":
        pos_id = request.POST.get('position')
        perfect_sub = PayeerSubtract.objects.filter(pk=(int(pos_id)))[0]

        if (perfect_sub.visible == True and perfect_sub.end == False):
            PayeerSubtract.objects.filter(pk=perfect_sub.pk).update(visible=False, end=True)

            account = 'P1012357967'
            api_id = '792548463'
            api_pass = 'j9d6BAvRGowgJyNN'

            endmoney = (perfect_sub.money - (float(perfect_sub.money) * float(3.5) / 100))
            #
            # Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(obtaining_money=F("obtaining_money") - perfect_sub.money)
            # Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(pay_del=F("pay_del") + perfect_sub.money)

            # Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(zarab_usd=F("zarab_usd") - perfect_sub.money)
            # Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(pay_del=F("pay_del") + perfect_sub.money)

            if perfect_sub.refka == False:

                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(
                    zarab_usd=F("zarab_usd") - perfect_sub.money)
                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(
                    out_usd=F("out_usd") + perfect_sub.money)

            else:

                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(
                    bonus_usd=F("bonus_usd") - perfect_sub.money)
                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(
                    out_bonus_usd=F("out_bonus_usd") + perfect_sub.money)

            PayeerApi(account, api_id, api_pass).transfer(sum=round(endmoney, 2), to=str(perfect_sub.purse), cur_in='USD', cur_out='USD', comment='Deltus.biz')
            return redirect(request.path)


    context = {

        'payeer_outputs': payeer_outputs,
        'balanse_payeer': balanse_payeer,

    }

    return render(request, 'panel_payeer_output.html', context)


def panel_history_usd(request):

    historys = HistoryUsd.objects.filter(datetime=date.today()).order_by('-id')

    context = {

        'historys': historys,

    }
    return render(request, 'panel_history_usd.html', context)

apps/panel/templates/panel.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Панель</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="index.html">Главная</a>&nbsp;<i class="fa fa-angle-right"></i></li>
                        <li class="active">Панель</li>
                    </ol>
                </div>
            </div>

            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Финансы:</div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12 col-12">
                    <div class="card">
                        <div class="panel-body">
                            <div class="text-center">
                                <h3>Payeer</h3>
                                <hr>
                                <h3> <b>${{ balanse_payeer }}</b></h3>
                                <hr>

                                <a href="{% url 'panel:panel_payeer_output' %}">
                                    <button type="button" class="btn btn-circle btn-default">Вывод</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-12 col-12">
                    <div class="card">
                        <div class="panel-body">
                            <div class="text-center">
                                <h3>Perfect</h3>
                                <hr>
                                <h3> <b>${{ pr_balans_perfect }}</b></h3>
                                <hr>

                                <a href="{% url 'money:perfect_admin' %}">
                                    <button type="button" class="btn btn-circle btn-default">Вывод</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Маркетинг:</div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12 col-12">
                    <div class="card">
                        <div class="panel-body">
                            <div class="text-center">
                                <h3>Депозити</h3>
                                <hr>
                                <a href="{% url 'panel:panel_deposit' %}">
                                    <button type="button" class="btn btn-circle btn-default">Открить</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


                 </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="profile-sidebar" style="padding-bottom: 100px">
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

apps/panel/templates/panel_deposit.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Личный кабинет</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="index.html">Главная</a>&nbsp;<i class="fa fa-angle-right"></i></li>
                        <li class="active">Личный кабинет</li>
                    </ol>
                </div>
            </div>
            <div class="row">

                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                    <div class="card">
                        <div class="panel-body">
                            <h3>USD:</h3>
                            <h4>%{{ cat_usd }}</h4>
                            <hr>
                            <h4>Количество депозитов которые должны получить выплату: <b>{{ count_active_deposit_usd }}</b></h4>
                            <h4>Количество депозитов не активных пользователей: <b>{{ count_active_deposit_no_active_user_usd }}</b></h4>
                            <h4>Количество всех депозитов: <b>{{ count_all_deposit }}</b></h4>
                            <hr>
                            <h4>Количество записей в истории за день по депозитам: <b>{{ count_history_usd }}</b></h4>
                            <hr>

                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="name_category" value="usd">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                            <input class = "mdl-textfield__input" type="number" name="liva">
                                            <label class = "mdl-textfield__label">От</label>
                                        </div>
                                        <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
                                            <input class = "mdl-textfield__input" type="number" name="prava">
                                            <label class = "mdl-textfield__label">По</label>
                                        </div>
                                    </div>
                                    <div class="col-lg-6" style="padding-top: 22px">
                                        <button type="submit" class="btn dark btn-outline btn-circle m-b-10">Активировать Usd</button>
                                        <p style="color: red">Нумерация начинается с 0 и до числа которое хотите</p>
                                    </div>
                                </div>
                            </form>
                            <hr>
                            <a href="{% url 'panel:panel_history_usd' %}">История</a>
                            <hr>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                    <div class="card">
                        <div class="panel-body">

                            <p>Count User = {{ count_all_user }}</p>
                            <p>count Active User = {{ count_active_user }}</p>

                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="name_category" value="active_user">
                                <button class="btn-rounded btn-outline-primary" type="submit"> <b> Перевести все кнопки пользователей в неактивные </b></button>
                            </form>


                        </div>
                    </div>
                </div>



                <div class="col-md-4">
{#                    <p>Count_user = {{ count_all_user }}</p>#}
{#                    <p>count_active_user = {{ count_active_user }}</p>#}
{#                    <p>Count_usd = {{ count_usd_depos }}</p>#}
{#                    <p>Count_bcd = {{ count_btc_depos }}</p>#}
{#                    <form method="post">#}
{#                        {% csrf_token %}#}
{#                        <input type="hidden" name="name_category" value="usd">#}
{#                        <button style="width:400px; height:50px;" class="btn-rounded btn-outline-primary" type="submit"> <b> Start USD </b></button>#}
{#                    </form>#}
{#                    <form method="post">#}
{#                        {% csrf_token %}#}
{#                        <input type="hidden" name="name_category" value="bts">#}
{#                        <button style="width:400px; height:50px;" class="btn-rounded btn-outline-primary" type="submit"> <b> Start BTC </b></button>#}
{#                    </form>#}
{#                    <form method="post">#}
{#                        {% csrf_token %}#}
{#                        <input type="hidden" name="name_category" value="active_user">#}
{#                        <button style="width:400px; height:50px;" class="btn-rounded btn-outline-primary" type="submit"> <b> Занулить пользователей </b></button>#}
{#                    </form>#}

                 </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="profile-sidebar" style="padding-bottom: 100px">
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

apps/panel/templates/panel_history_usd.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Панель</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="index.html">Главная</a>&nbsp;<i class="fa fa-angle-right"></i></li>
                        <li class="active">История USD</li>
                    </ol>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <table class="table display product-overview mb-30" id="support_table5">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Users</th>
                                <th>Category</th>
                                <th>Sponsor</th>
                                <th>Maseger</th>
                                <th>Number</th>
                                <th>Plus</th>
                                <th>Bonus</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for history in historys %}
                            <tr>
                                <td>{{ history.id }}</td>
                                <td>{{ history.users }}</td>
                                <td>{{ history.category }}</td>
                                <td>{{ history.sponsor }}</td>
                                <td>{{ history.maseger }}</td>
                                <td>{{ history.number }}</td>
                                <td>{{ history.plus }}</td>
                                <td>{{ history.bonus }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


                 </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="profile-sidebar" style="padding-bottom: 100px">
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

apps/panel/templates/panel_payeer_output.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
   {% if request.user.is_superuser %}
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">

        <div class="col-md-12">
            <h3>Панель управления</h3>
            <h5> Баланс Payeer ${{ balanse_payeer }} </h5>
            <hr>
            <div class="col-md-12">
                <div class="card card-accent-theme">
                    <div class=" products-widget">

                <div class="container-fluid">

                             <div class="col-md-12 col-sm-12 col-xs-12 marg-money">

                                 <table class="table table-condensed text-left">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>User</th>
                                        <th>Дата</th>
                                        <th>Вивести</th>
                                        <th>(хотят)</th>
                                        <th>Кошелек</th>


{#                                        <th>Игра</th>#}
{#                                        <th>Вивод</th>#}
{#                                        #}
{#                                        <th>Кошелек</th>#}
{#                                        #}
{#                                        <th>Пополнил</th>#}
{#                                        <th>Перевели</th>#}
{#                                        <th>Вивел</th>#}
{#                                        <th>Зараб матрица</th>#}
{#                                        <th>Зараб бонуси</th>#}
{#                                        <th>Отправлено средств</th>#}

                                    </tr>
                                    </thead>
                                    <tbody>

                                        {% for payeer in payeer_outputs %}
                                            <form method="post"  prefix='banned'>
                                            {% csrf_token %}
                                            <input type="hidden" name="position" value="{{ payeer.pk }}">

                                            <tr>
                                                <td style="text-align:center">{{ payeer.id }}</td>
                                                <td>[{{ payeer.user.profile.pk }}] {{ payeer.user }}</td>
                                                <td>{{ payeer.datetime|date:'d-m-Y' }}</td>
                                                <td>
                                                    <button class="btn"> ok </button>
                                                </td>

                                                <td>
                                                    <font color="red" size="3"> <b>${{ payeer.money }}</b> </font>
                                                </td>

                                                {% if payeer.refka == True %}
                                                    <td>
                                                        <font color="#8b008b" size="3"> <b>Партнерские </b> </font>
                                                    </td>
                                                    {% else %}
                                                    <td>
                                                        <font color="#8b008b" size="3"> <b>Баланс вывода</b> </font>
                                                    </td>
                                                {% endif %}


{#                                                <td>${{ payeer.user.profile.expense }}</td>#}
{#                                                <td>#}
{#                                                    <font color="#1e90ff" size="3"> <b>${{  payeer.user.profile.obtaining_money }}</b> </font>#}
{#                                                </td>#}
{##}
                            {#                    <td>${{ payeer.user.profile.bali }}</td>#}
{##}
{#                                                <td>#}
{#                                                    <font color="red" size="3"> <b>${{  payeer.money }}</b> </font>#}
{#                                                </td>#}
{##}
{#                                                <td>{{ payeer.purse }}</td>#}
{##}
{##}
{#                                                #}
{#                                                <td>#}
{#                                                    <font color="green" size="3"> <b>${{ payeer.user.profile.pay_add }}</b> </font>#}
{#                                                </td>#}
{##}
{#                                                <td>#}
{#                                                    <font color="green" size="3"> <b>${{ payeer.user.profile.transfer_user_got }}</b> </font>#}
{#                                                </td>#}
{##}
{#                                                <td>#}
{#                                                    <font color="red" size="3"> <b>${{ payeer.user.profile.pay_del }}</b> </font>#}
{#                                                </td>#}
{##}
{#                                                <td>#}
{#                                                    <font color="#ffd700" size="3"> <b>${{ payeer.user.profile.zarab_matrix }}</b> </font>#}
{#                                                </td>#}
{##}
{#                                                <td>#}
{#                                                    <font color="#8b008b" size="3"> <b>${{ payeer.user.profile.matrix_bon_zara }}</b> </font>#}
{#                                                </td>#}
{##}
{#                                                <td>#}
{#                                                    <font color="#8b008b" size="3"> <b>${{ payeer.user.profile.transfer_expense_in_user }}</b> </font>#}
{#                                                </td>#}

                                            </tr>
                                            </form>
                                        {% endfor %}

                                    </tbody>
                                </table>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                </div>
            </div>
        </div>
    </div>

    {% endif %}
{% endblock %}