apps/money/urls.py
from django.conf.urls import url

from apps.money import views


urlpatterns = [

    url(r'^refill/$', views.refill, name='refill'),

    url(r'^issuance/$', views.issuance, name='issuance'),

    url(r'^refill-perfect/$', views.refill_perfect, name='refill_perfect'),

    url(r'^refill-payeer/$', views.refill_payeer, name='refill_payeer'),

    url(r'^refill-perfect/ok/$', views.refill_perfect_add, name='refill_perfect_ok'),

    url(r'^refill-perfect/(?P<perfect_pk>\w+)/$', views.refill_perfect_add, name='refill_perfect_add'),

    url(r'^refill-payeer/yes/$', views.refill_payeer_add, name='refill_payeer_add'),

    url(r'^issuance-perfect/$', views.issuance_perfect, name='issuance_perfect'),

    url(r'^issuance-payeer/$', views.issuance_payeer, name='issuance_payeer'),


    url(r'^perfect/admin/$', views.perfect_admin, name='perfect_admin'),



    url(r'^transfer/$', views.transfer_money, name='transfer_money'),

    url(r'^transferkopilka/$', views.transferkopilka, name='transferkopilka'),

    url(r'^transfervivod/$', views.transfervivod, name='transfervivod'),

    url(r'^transferuser/$', views.transferuser, name='transferuser'),

    url(r'^transfer/ok/$', views.transfer_money_ok, name='transfer_money_ok'),

    url(r'^transfer/ok/vivod/$', views.transfer_money_ok_vivod, name='transfer_money_ok_vivod'),

    url(r'^transfer/no/$', views.transfer_money_no, name='transfer_money_no'),


    url(r'^transfer/expense/bali/$', views.transfer_money_expense_in_bali, name='transfer_money_expense_in_bali'),

    url(r'^transfer/expense/bali/basket/$', views.transfer_money_expense_in_bali_basket, name='transfer_money_expense_in_bali_basket'),







    url(r'^transfer/obtaining/in/expense/$', views.transfer_money_vivod_in_activation, name='transfer_money_vivod_in_activation'),

    url(r'^transfer/obtaining/in/expense/basket/$', views.transfer_money_vivod_in_activation_basket, name='transfer_money_vivod_in_activation_basket'),


    url(r'^transfer/bali/in/expense/$', views.transfer_bali_in_activation, name='transfer_bali_in_activation'),

    url(r'^transfer/bali/in/expense/basket/$', views.transfer_bali_in_activation_basket, name='transfer_bali_in_activation_basket'),


    url(r'^transfer/obtaining/in/expense/user$', views.transfer_vivod_in_activation_user, name='transfer_vivod_in_activation_user'),

    url(r'^transfer/obtaining/in/expense/user/basket/$', views.transfer_vivod_in_activation_user_basket, name='transfer_bali_in_activation_basket'),

]

apps/user/urls.py
from django.conf.urls import url

from apps.user import views


urlpatterns = [

    url(r'^register/$', views.stsignup, name='stregister'),

    url(r'^register/(?P<user_pk>\d+)/$', views.signup , name='register'),

    url(r'^profile/$', views.profile, name='profile'),

    url(r'^redirect/',views.user_redirect, name='user_redirect'),

    url(r'^info/(?P<user_id>\d+)/$', views.info, name='info'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
]

investment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
# urlpatterns = (
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    url(r'^', include(('apps.home.urls', 'home'), namespace='home')),
    url(r'^user/', include(('apps.user.urls', 'user'), namespace='user')),
    url(r'^money/', include(('apps.money.urls', 'money'), namespace='money')),
    url(r'^referrals/', include(('apps.referrals.urls', 'referrals'), namespace='referrals')),
    url(r'^deposit/', include(('apps.deposit.urls', 'deposit'), namespace='deposit')),
    url(r'^panel/', include(('apps.panel.urls', 'panel'), namespace='panel')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
)

apps/money/forms.py
from django import forms
from apps.money.models import *


class PerfectAddForm(forms.ModelForm):
    class Meta:
        model = PerfectAdd
        fields = ('money',)
        exclude = ('user','key',)


class PayeerAddForm(forms.ModelForm):
    class Meta:
        model = PayeerAdd
        fields = ('money',)
        exclude = ('user', 'key', 'pay_signature',)


class PerfectSubtractForm(forms.ModelForm):
    class Meta:
        model = PerfectSubtract
        fields = ('money',)
        exclude = ('user',)

class PayeerSubtractForm(forms.ModelForm):
    class Meta:
        model = PayeerSubtract
        fields = ('money',)
        exclude = ('user',)


class TransferObtainingMoneyForm(forms.ModelForm):
    class Meta:
        model = TransferObtainingMoney
        fields = ('money','user_name',)
        exclude = ('user',)


class InternalTranslationForm(forms.ModelForm):
    class Meta:
        model = InternalTranslation
        fields = ('moneys',)
        exclude = ('user',)


class TransferPiggyBanksForm(forms.ModelForm):
    class Meta:
        model = TransferPiggyBanks
        fields = ('moneys',)
        exclude = ('user',)


class TransferExpenseForm(forms.ModelForm):
    class Meta:
        model = TransferExpenMoney
        fields = ('money',)
        exclude = ('user','payments','datetime',)


class TransferVivodInActivationForm(forms.ModelForm):
    class Meta:
        model = InternalTranslation
        fields = ('moneys',)
        exclude = ('user','datetime',)


class TransferBaliInActivationForm(forms.ModelForm):
    class Meta:
        model = TransferPiggyBanks
        fields = ('moneys',)
        exclude = ('user','datetime',)


class TransferVivodInActivationUserForm(forms.ModelForm):
    class Meta:
        model = TransferObtainingMoney
        fields = ('money','transfer_user','user_name',)
        exclude = ('user','datetime',)

apps/money/views.py
# coding=utf-8
import datetime
from _sha256 import sha256

from django.contrib.auth.decorators import login_required
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.db.models import F
from django.shortcuts import render, redirect

from apps.money.PerfectMoney import PerfectMoney
from apps.payeer.api import payeer_api

from apps.money.forms import *
from apps.user.models import Profile

from apps.payeer.constants import CURRENCY_USD


def get_balance(account, password):
    pm = PerfectMoney(account, password)
    res = pm.balance()
    return res

def transfer_moneys(account, password, payer, payee, amount, memo, payment_id):
    pm = PerfectMoney(account, password)
    res = pm.transfer(payer, payee, amount, memo, payment_id)
    return res


@login_required
def refill(request):

    print("Chec")

    # from coinpayments import CoinPaymentsAPI
    # api = CoinPaymentsAPI(public_key='f6cc952c2f0c60e7287141cfc649ed913d7bb2f70ecf461d016f2de6f5509b58',
    #                       private_key='31aAA72748Aea82c08993997d0Eb57A20734cAe44872803aA52752E3D4885654')

    # from coinpayments import CoinPaymentsAPI
    # api = CoinPaymentsAPI(public_key='e6a939f5210909d8b592f70b146a736d23dccd19364877be808860a773a441d6',
    #                       private_key='E1291680A662FcC5D1E506B228b0BdEC744Ccf932c5292ca9976451D555e997A')
    #
    # print(api.check_signature('CPDE1AC7E7BJSEZM8S0WOA1WTK', 'CPDE1AC7E7BJSEZM8S0WOA1WTK'))
    # print(api.get_deposit_address())
    # print(api.rates())
    # print(api.get_basic_info())

    # print(api.check_signature('CPDE4KQKM2UNTPLOBESWTOCQBV','CPDE4KQKM2UNTPLOBESWTOCQBV'))
    # print(api.rates())
    # print(api.check_signature('3MUb4BQ5ZUsS3QGDa9ojrG6AeaSVHxqN6g', 'CPDE4KQKM2UNTPLOBESWTOCQBV'))
    # api.rates()
    # api.check_signature('ipn_message', 'ipn signautre')
    # api.check_signature('ipn_message', 'ipn signautre')

    # print("End chec")

    context = {
    }
    return render(request, 'refill.html', context)


@login_required
def issuance(request):

    context = {
    }
    return render(request, 'issuance.html', context)



@login_required
def perfect_admin(request):
    account = '3310706'
    password = 'zN3Ht7vV'

    pm = PerfectMoney(account, password)
    res = pm.balance()
    pr_balans_perfect = str(res.get('U19769559'))

    all_perfects = PerfectSubtract.objects.filter(visible=True)

    if request.method == "POST":
        pos_id = request.POST.get('position')

        perfect_sub = PerfectSubtract.objects.filter(pk=(int(pos_id)))[0]

        if (perfect_sub.visible == True):
            PerfectSubtract.objects.filter(pk=perfect_sub.pk).update(end=True, visible=False)

            account = '3310706'
            password = 'zN3Ht7vV'

            payer = 'U19769559'

            count = PerfectSubtract.objects.all().count()
            name_user = perfect_sub.user

            money = perfect_sub.money
            user_payer = perfect_sub.purse

            komisia = (float(perfect_sub.money) * float(3.5) / 100)
            print(komisia)
            endmoney = (money - komisia)
            print(endmoney)

            get_balance(account, password)
            if perfect_sub.refka == False:

                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(zarab_usd=F("zarab_usd") - perfect_sub.money)
                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(out_usd=F("out_usd") + perfect_sub.money)

            else:

                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(
                    bonus_usd=F("bonus_usd") - perfect_sub.money)
                Profile.objects.filter(pk=perfect_sub.user.profile.pk).update(
                    out_bonus_usd=F("out_bonus_usd") + perfect_sub.money)

            transfer_moneys(account, password, payer, user_payer, round(endmoney, 2), str(name_user), int(count))

            return redirect(request.path)

        else:
            return redirect('/money/transfer/no/')

    context = {

        'pr_balans_perfect':pr_balans_perfect,
        'all_perfects':all_perfects,

    }

    return render(request, 'perfect_admin.html', context)



@login_required
def refill_perfect(request):

    money = '0'
    url = ''
    sing = ''
    name_button = 'Подтвердить'

    end_refill_perfect = PerfectAdd.objects.filter(user=request.user, visible=True).order_by('-id')

    perfect_count = PerfectAdd.objects.all().count()

    form = PerfectAddForm
    if request.method == "POST":
        form = PerfectAddForm(request.POST)
        if form.is_valid():
            inst = form.save(commit=False)
            inst.user = request.user
            now = datetime.datetime.now()
            inst.datetime = now

            PAYEE_ACCOUNT = 'U19769559'
            PAYEE_NAME = 'Deltus.biz'
            PAYMENT_UNITS = 'USD'
            STATUS_URL = 'http://deltus.biz/money/refill-perfect/'
            PAYMENT_URL = 'http://deltus.biz/money/refill-perfect/ok/'
            NOPAYMENT_URL = 'http://deltus.biz/ru/info/'
            PAYMENT_AMOUNT = str(inst.money) + str(request.user) + str(perfect_count)

            hash = "{}:{}:{}:{}:{}:{}:{}".format(PAYEE_ACCOUNT,
                                                 PAYEE_NAME,
                                                 PAYMENT_UNITS,
                                                 STATUS_URL,
                                                 PAYMENT_URL,
                                                 NOPAYMENT_URL,
                                                 PAYMENT_AMOUNT
                                                 )

            sign_hash = sha256(hash.encode())
            sing = sign_hash.hexdigest().upper()


            inst.key = sing
            inst.save()

            url = 'https://perfectmoney.is/api/step1.asp'
            money = inst.money
            name_button = 'Оплатить'


    context = {

        'sing': sing,
        'url': url,
        'form': form,
        'money': money,
        'name_button': name_button,
        'end_refill_perfect': end_refill_perfect,

    }

    return render(request, 'refill_perfect.html', context)


@login_required
def merchant(request):

    return render(request, 'refill_perfect.html')


def refill_perfect_ok(request):

    context = {
    }

    return render(request, 'refill_perfect_ok.html', context)


@login_required
def refill_perfect_add(request, perfect_pk):

    refill = PerfectAdd.objects.filter(user=request.user, visible=False).order_by('-id')[0]
    if (refill.visible == False and refill.key == perfect_pk):
        PerfectAdd.objects.filter(pk=refill.pk).update(visible=True)

        Profile.objects.filter(user=refill.user).update(balance_usd=F('balance_usd') + float(refill.money))
        Profile.objects.filter(user=refill.user).update(filled_usd=F('filled_usd') + float(refill.money))

    context = {

        'refill': refill,

    }
    return render(request, 'refill_perfect_add.html', context)


def toFixed(numObj, digits=0):
    return f"{numObj:.{digits}f}"


@login_required
def refill_payeer(request):

    end_refill_payeers = PayeerAdd.objects.filter(user=request.user, end=True).order_by('-id')

    form = PayeerAddForm
    if request.method == "POST":
        form = PayeerAddForm(request.POST)
        if form.is_valid():
            inst = form.save(commit=False)
            inst.user = request.user

            count_payeer = PayeerAdd.objects.all().count()

            description = 'Popolnenia ' + str(inst.user)

            data = payeer_api.merchant(
                order_id=count_payeer,
                amount=inst.money,
                currency=CURRENCY_USD,
                description=description
            )

            inst.order_id = count_payeer
            inst.amount = inst.money
            inst.currency = CURRENCY_USD
            inst.description = description

            import datetime
            dat = datetime.datetime.now()

            hash = "{}:{}:{}:{}:{}:{}:{}:{}:{}".format(
                count_payeer,
                CURRENCY_USD,
                description,
                'DRiej12pXOM3KoHc',
                'DRiejdd12pXOM3KoHcUsas',
                float(1111),
                dat.day,
                dat.month,
                dat.year,
                request.user
            )

            sign_hash = sha256(hash.encode())
            sing = sign_hash.hexdigest().upper()

            inst.key = str(sing)

            now = datetime.datetime.now()
            inst.datetime = now

            inst.save()

            return redirect(data.get('location'))

    context = {

        'end_refill_payeers': end_refill_payeers,
        'form': form,

    }

    return render(request, 'refill_payeer.html', context)


@login_required
def refill_payeer_add(request):

    m_orderid = str(request.GET.get('m_orderid'))
    description = 'Popolnenia ' + str(request.user)
    dat = datetime.datetime.now()

    hash = "{}:{}:{}:{}:{}:{}:{}:{}:{}".format(
        m_orderid,
        CURRENCY_USD,
        description,
        'DRiej12pXOM3KoHc',
        'DRiejdd12pXOM3KoHcUsas',
        float(1111),
        dat.day,
        dat.month,
        dat.year,
        request.user
    )

    sign_hash = sha256(hash.encode())
    sing = sign_hash.hexdigest().upper()

    # description = 'Popolnenia ' + str(request.user)
    # order_id = request.GET.get('m_orderid')
    # amount = request.GET.get('m_amount')
    # currency = request.GET.get('m_curr')
    # desc_str = payeer_api.generate_description(description)
    #
    # all_end_sign = payeer_api.generate_signature(order_id, amount, currency, desc_str)
    #
    #
    #
    # description = 'Popolnenia ' + str(request.user)
    # m_orderid = request.GET.get('m_orderid')
    # m_amount = request.GET.get('m_amount')
    # m_curr = request.GET.get('m_curr')
    # m_desc = request.GET.get('m_desc')
    # # Генерация сигнатури

apps/money/templates/refill.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div style="padding-left: 40px" class="page-title">Пополнения</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                        <li><i class="fa fa-home"></i>&nbsp;<a class="parent-item" href="{% url 'user:profile' %}">Кабинет</a>&nbsp;<i class="fa fa-angle-right"></i></li>
                        <li class="active">Пополнения</li>
                    </ol>
                </div>
            </div>
                <div class="row">
                    <div class="col-md-4" style="padding-left: 50px">
                        <div class="card card-box text-center">
                            <a href="{% url 'money:refill_payeer' %}">
                                <img src="/static/panel/assets/img/payeer.png" style="width: 250px">
                            </a>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card  card-box text-center">
                            <a href="{% url 'money:refill_perfect' %}">
                                <img src="/static/panel/assets/img/pm.png" style="width: 250px">
                            </a>
                        </div>
                    </div>


{#                    <form action="https://www.coinpayments.net/index.php" method="post">#}
{#                        <input type="hidden" name="cmd" value="_pay_simple">#}
{#                        <input type="hidden" name="reset" value="1">#}
{#                        <input type="hidden" name="merchant" value="142cd1c4336f93de27c679d46d24b3a4">#}
{#                        <input type="hidden" name="item_name" value="testing">#}
{#                        <input type="hidden" name="currency" value="BTC">#}
{#                        <input type="text" name="amountf" value="1.00000000">#}
{#                        <input type="hidden" name="want_shipping" value="0">#}
{#                        <input type="image" src="https://www.coinpayments.net/images/pub/buynow-grey.png" alt="Купить используя CoinPayments.net">#}
{#                    </form>#}
{##}
{#                    <div class=" products-widget">#}
{#                        <div class="col-md-12">#}
{#                            <br>#}
{#                            <h5><a href="{% url 'money:refill_perfect' %}">Пополнения Perfect Money</a></h5>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
    </div>

{#    </main>#}

{#    <main class="main">#}
{#        <ol class="breadcrumb bc-colored bg-theme" id="breadcrumb">#}
{#            <li class="breadcrumb-item ">#}
{#                <a href="{% url 'user:profile' %}">Аккаунт</a>#}
{#            </li>#}
{#            <li class="breadcrumb-item active">Пополнения</li>#}
{#        </ol>#}
{#        <div class="col-md-12">#}
{#            <h3>Пополнения</h3>#}
{#            <hr>#}
{#            <h3 class="item-name"><a href="{% url 'money:refill_payeer' %}"><font size="5">Payeer</font></a></h3>#}
{#        </div>#}
{##}
{##}
{#        <div class="col-md-12 col-sm-12 col-xs-12 marg-money">#}
{#            <br>#}
{#            <header class="content-title">#}
{#                <div class="title-bg">#}
{#                    <h2 class="title">Пополнения счета</h2>#}
{#                </div>#}
{#                <p class="title-desc">Основная валюта сайта доллары.</p>#}
{#            </header>#}
{#            <br>#}
{#            <div class="col-md-12 col-sm-12 col-xs-12">#}
{#                <div class="col-md-3 col-sm-6 col-xs-12">#}
{#                    <div class="item item-hover services-box">#}
{#                        <div class="item-image-wrapper">#}
{#                            <figure class="item-image-container">#}
{#                                <a href="{% url 'money:refill_perfect' %}">#}
{#                                    <p><img src="{{ IMG_URL }}site/perfect3.jpg" alt="item1" class="item-image" width="10" height="10"></p>#}
{#                                    <img src="{{ IMG_URL }}site/perfect3.jpg" alt="item1  Hover" class="item-image-hover">#}
{#                                </a>#}
{#                            </figure>#}
{#                        </div>#}
{#                        <div class="item-meta-container">#}
{#                            <h3 class="item-name"><a href="{% url 'money:refill_perfect' %}"><font size="5">Perfect Money</font></a></h3>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="col-md-6 col-sm-6 col-xs-6">#}
{#                <hr>#}
{#                <h3>История Пополнения (Perfect Money):</h3>#}
{#                <table class="table table-condensed text-left">#}
{#                    <thead>#}
{#                    <tr>#}
{#                        <th>ID</th>#}
{#                        <th>Cумма</th>#}
{#                    </tr>#}
{#                    </thead>#}
{#                    <tbody>#}
{##}
{#                        {% for perfect in perfect_add %}#}
{#                            <tr>#}
{#                                <td style="text-align:center">{{ perfect.id }}</td>#}
{#                                <td>${{ perfect.money }}</td>#}
{#                            </tr>#}
{#                        {% endfor %}#}
{##}
{#                    </tbody>#}
{#                </table>#}
{##}
{#                <h4>Общая сумма пополнения: ${{ perf_add_suma }}</h4>#}
{##}
{#                <div class="pagination-container clearfix">#}
{#                     <div class="pull-left page-count">#}
{#                         <br>#}
{#                         Cтраница {{ perfect_add.number }} из {{ perfect_add.paginator.num_pages }}#}
{#                     </div>#}
{##}
{#                     <div class="pull-right">#}
{#                         <ul class="pagination">#}
{#                             {% if perfect_add.has_previous %}#}
{#                                 <li><a href="?page={{ perfect_add.previous_page_number }}">«</a></li>#}
{#                             {% endif %}#}
{#                             <li><a href="">{{ perfect_add.number }}</a></li>#}
{#                             {% if perfect_add.has_next %}#}
{#                                 <li><a href="?page={{ perfect_add.next_page_number }}">»</a></li>#}
{#                             {% endif %}#}
{#                         </ul>#}
{#                     </div>#}
{#                </div>#}
{#            </div>#}
{##}
{#        </div>#}
{#    </div>#}
{#    </main>#}
{% endblock %}

apps/money/templates/refill_payeer.html
{% extends 'base_panel.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}

     <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">

            </div>


    <main class="main">
    <div class="offset-md-8">
        <ol class="breadcrumb bc-colored bg-theme" id="breadcrumb">
            <li class="breadcrumb-item ">
                <a href="{% url 'user:profile' %}">Аккаунт</a>
            </li>
            <li class="breadcrumb-item active">Пополнения счета Payeer</li>
        </ol>
    </div>
        <div class="offset-md-3 col-md-8">
            <h3 style="padding-left: 120px">Пополнения счета Payeer</h3>
            <hr>
            <div class="col-md-8">
                    <div class="card  card-box">
                        <div class="col-md-12">
                            <br>
                            <form method="post">
                                 {% csrf_token %}
                                 <h5>Сумма:&#42;</h5>
                                 {{ form.money|add_class:'form-control input-lg'}}

                                 <div class="col-xs-12 col-md-12 col-sm-12 " style="padding-bottom: 10px">
                                     <br>
                                    <button  class="btn btn-primary" type="submit"> <b> Пополнить </b></button>
                                </div>
                             </form>
                        </div>
                    </div>
            </div>
        </div>
        <div class="offset-md-3 col-md-8">
            <div class="col-md-8">
                <div class="card  card-box">
                    <div class=" products-widget">
                        <div class="col-md-12">
                            <br>
                            <h5>История Пополнения (Payeer):</h5>
                            <hr>
                            {% for end_refill_payeer in end_refill_payeers %}
                                <p>Id: {{ end_refill_payeer.id }} | <b>Sum: {{ end_refill_payeer.money }}</b> | {{ end_refill_payeer.datetime|date:'d-m-Y' }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{#    <div class="container">#}
{#         <div class="col-md-12 col-sm-12 col-xs-12 marg-money">#}
{#             <br>#}
{#             <header class="content-title">#}
{#                <div class="title-bg">#}
{#                    <h2 class="title">Пополнения счета Payeer</h2>#}
{#                </div>#}
{#                <p class="title-desc">Основная валюта сайта доллары.</p>#}
{#             </header>#}
{#             <br>#}
{#             <div class="col-md-12 col-sm-12 col-xs-12">#}
{#                 <div class="col-md-3 col-sm-3 col-xs-12">#}
{#                     <p><img src="{{ IMG_URL }}site/payeer.png" alt="item1" class="item-image" width="200" height="200"></p>#}
{#                 </div>#}
{#                 <div class="col-md-3 col-sm-3 col-xs-12">#}
{#<div class="col-md-12 col-sm-12 col-xs-12">#}
{##}
{#             <div class="col-md-12 col-sm-12 col-xs-12">#}
{#                 <div class="col-md-12 col-sm-12 col-xs-12 text-center">#}
{#                     <img src="{{ IMG_URL }}site/payeer.png" alt="Payeer">#}
{#                 </div>#}
{#                 <div class="col-md-12 col-sm-12 col-xs-12 text-center">#}
{#                     <form method="post">#}
{#                         {% csrf_token %}#}
{#                         <span class="input-group-addon"><span class="input-icon input-icon-subject"></span><span class="input-text">Сумма:&#42;</span></span>#}
{#                         {{ form.money|add_class:'form-control input-lg'}}#}
{##}
{#                         <div class="col-xs-12 col-md-12 col-sm-12 ">#}
{#                             <br>#}
{#                            <button  class="btn btn-primary" type="submit"> <b> Пополнить </b></button>#}
{#                        </div>#}
{#                     </form>#}
{#                 </div>#}
{#             </div>#}
{#         </div>#}
{##}
{##}
{##}
{#                 </div>#}
{#             </div>#}
{#         </div>#}
{#    </div>#}

{% endblock %}

apps/money/templates/transfer_money.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <main class="main">
        <ol class="breadcrumb bc-colored bg-theme" id="breadcrumb">
            <li class="breadcrumb-item active">Аккаунт</li>
        </ol>
        <br>
        <div class="container-fluid">
            <div class="animated fadeIn">
                <div class="row">
        <br>
        <div class="col-md-12 col-sm-12 col-xs-12 text-center">

{#                <div class="col-md-6 col-sm-6 col-xs-12 text-center">#}
{#                    <div class="brd-transfer">#}
{#                        <br>#}
{#                        <h2>Перевод средств с Копилки на покупку Ключей</h2>#}
{#                        <a href="{% url 'money:transfer_bali_in_activation' %}"><button class="btn btn-custom-2">Перевести</button></a>#}
{#                    </div>#}
{#                </div>#}
                    <div class="col-md-12">
                        <div class="card card-accent-theme">
                            <div class=" products-widget">
                                <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                    <div class="brd-transfer">
                                        <br>
                                        <h5>Перевод средств с Баланса Вывода на Баланс Покупок</h5>
                                        <a href="{% url 'money:transfer_money_vivod_in_activation' %}"><button class="btn btn-primary btn-round">Перевести</button></a>
                                        <br>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{##}
{#             <div class="col-md-6 col-sm-6 col-xs-12 text-center">#}
{#                <div class="brd-transfer">#}
{#                    <br>#}
{#                    <h2>Перевод средств с Баланса Активацию на Баланс Копилки</h2>#}
{#                    <a href="{% url 'money:transfer_money_expense_in_bali' %}"><button class="btn btn-custom-2">Перевести</button></a>#}
{#                </div>#}
{#             </div>#}
{##}
            <div class="col-md-12">
                <div class="card card-accent-theme">
                    <div class=" products-widget">
                         <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                            <div class="brd-transfer">
                                <br>
                                <h5>Перевод средств с Баланса Покупок другому пользователю</h5>
                                <a href="{% url 'money:transfer_vivod_in_activation_user' %}"><button class="btn btn-primary btn-round">Перевести</button></a>
                                <br>
                            </div>
                         </div>
                    </div>
                </div>
            </div>

        </div>
    </di>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

apps/money/templates/transfer_money_no.html
{% extends 'base_admin.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block content %}
    <div class="container">
         <div class="col-md-12 col-sm-12 col-xs-12 marg-money">
             <br>
             <header class="content-title">
                <div class="title-bg">
                    <h2 class="title">У вас не хватает денег для вывода. Минимальная сумма $1</h2>
                </div>
             </header>
             <br>
         </div>
    </div>
{% endblock %}